### ISSUE TITLE
cotnflict for python3.7 and networkx1.7

### ISSUE THREAD

**Issue by zsdxgl** [cgjosephlee/PBJelly#1]
I want to fill gap in my assembly by using PBJelly. However, errors always occur. And there is a report about a conflict between python3.7 and networkx1.7. Also, the method that using conda to intall PBJelly also failed. Would you please check again your version?

**Comment by cgjosephlee** [comment]
Can you post your error messages? I don't see errors or conflicts.

**Comment by zsdxgl** [comment]
**Dear Sir/Madam,

Sorry to disturb you. My description in the title is not clear. I have installed PBJelly as you described. The versions of blasr, python and networkx are 5.33, 3.7.3 and 1.7, respectively. 

There some errers in "python setup.py install " that caused by python. For example** 

SyntaxError: EOL while scanning string literal

  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pbjelly-16.0b1-py3.7.egg/pbsuite/utils/mapStats.py", line 113
    print "Subread Stats:"
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Subread Stats:")?


**I have corrected these errors.
However, new errer occurs in mapping.**

2019-12-04 15:18:06,316 [INFO] Running /home/leon/miniconda3/envs/PBJelly/bin/m4pie.py /DATA1/leon/M.pacbio/5.gapfill/mapping/Tov3.fastq.m4 /DATA1/leon/M.pacbio/5.gapfill/Tov3.fastq /DATA1/leon/M.pacbio/5.gapfill/ref.fasta --nproc 100 -i
Traceback (most recent call last):
  File "/home/leon/miniconda3/envs/PBJelly/bin/m4pie.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbjelly==16.0b1', 'm4pie.py')
  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pbjelly-16.0b1-py3.7.egg/EGG-INFO/scripts/m4pie.py", line 212, in <module>
    run(sys.argv[1:])
  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pbjelly-16.0b1-py3.7.egg/EGG-INFO/scripts/m4pie.py", line 173, in run
    aligns = M4File(args.m4)
  File "/home/leon/miniconda3/envs/PBJelly/lib/python3.7/site-packages/pbjelly-16.0b1-py3.7.egg/pbsuite/utils/FileHandlers.py", line 482, in __init__
    file = open(file,'r')
FileNotFoundError: [Errno 2] No such file or directory: '/DATA1/leon/M.pacbio/5.gapfill/mapping/Tov3.fastq.m4'

**Comment by zsdxgl** [comment]
Thanks for your quick reply. I have check the version of the software and dependent program. The softwares install as your instruciton would be OK. Now the program blasr is running. Thanks very much.

**Comment by cgjosephlee** [comment]
Glad to hear that. Feel free to ask here. I'm closing this for now, you may reopen if there are any questions.
